import { pascalCase } from "es-toolkit";
import type { CustomElementEntry, RuntimeOnlyEntry, SSREntry } from "../plugin";

export function safeComponentName(name: string, index: number) {
  const pc = pascalCase(name);
  if (/^[A-Z][A-Za-z0-9]*$/.test(pc)) {
    return pc;
  }
  console.warn(
    `[hyacine] Warning: Unsafe component name "${name}" converted to safe default "HyacineComponent${index}".`,
  );
  return `HyacineComponent${index}`;
}

function safeImportPath(path: string): string {
  // 使用 JSON 字符串字面量来避免引号/换行等导致的代码注入
  // 例：import X from "...";
  return JSON.stringify(path);
}

function safeHydrationInstruction(
  hydration: SSREntry["clientHydrationInstruction"],
): SSREntry["clientHydrationInstruction"] | undefined {
  // manifest 来自外部数据时，类型约束并不等于运行时安全；这里做白名单校验。
  if (
    hydration === "load" ||
    hydration === "idle" ||
    hydration === "visible" ||
    hydration === "media"
  ) {
    return hydration;
  }
  console.warn(
    `[hyacine] Warning: Invalid client hydration instruction "${hydration}" detected. Ignoring it for safety.`,
  );
  return undefined;
}

export function generateTempAstroTemplateFile(entries: (SSREntry | CustomElementEntry)[]): string {
  let importsArea = "";

  let usageArea = "";

  const seenPaths = new Set<string>();

  entries.forEach((entry, index) => {
    if (seenPaths.has(entry.path)) {
      console.warn(
        `[hyacine] Warning: Duplicate entry path "${entry.path}" detected. Skipping duplicate import.`,
      );
      return;
    }
    seenPaths.add(entry.path);

    const componentName = safeComponentName(entry.name, index);
    importsArea += `import ${componentName} from ${safeImportPath(entry.path)};\n`;

    if (entry.type === "custom-element") {
      usageArea += `<${componentName} style="display: none;" />\n`;
    } else if (entry.type === "ssr") {
      const hydration = safeHydrationInstruction(entry.clientHydrationInstruction);
      const hydrationAttr = hydration ? ` client:${hydration}` : "";
      usageArea += `<${componentName}${hydrationAttr} />\n`;
    }
  });

  return `
  ---
  //⚠️ This file is auto-generated by hyacine plugin system. Do not edit directly!
  // @ts-nocheck
  ${importsArea}
  ---
  <Fragment>
    ${usageArea}
  </Fragment>
  `.trim();
}

export function generateTempRuntimeFile(entries: RuntimeOnlyEntry[]): string {
  let importsArea = "";
  let initArea = "";

  const seenPaths = new Set<string>();

  entries.forEach((entry, index) => {
    if (seenPaths.has(entry.path)) return;
    seenPaths.add(entry.path);

    const componentName = safeComponentName(entry.name, index);
    const initAlias = `init_${componentName}`;
    importsArea += `import { init as ${initAlias} } from ${safeImportPath(entry.path)};\n`;
    initArea += `${initAlias}();\n`;
  });

  return `
  //⚠️ This file is auto-generated by hyacine plugin system. Do not edit directly!
  // @ts-nocheck
  
  ${importsArea}

  ${initArea}
  `.trim();
}
